development:
  encoding: unicode
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: timeclock_development
  password:

test:
  encoding: unicode
  adapter: postgresql
  username: postgres
  port: 5432
  host: localhost
  database: timeclock_test
  password:

production:
  encoding: unicode
  adapter: postgresql
  port: 5432
  host: localhost
  database: timeclock_production
  password:
